version: '3.1'

services:

  db:
    image: simpletodo-db
    restart: always
    volumes:
      - ./db/data:/bitnami/mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=admin
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_PASSWORD=example
      - MARIADB_DATABASE=simpletodo

  flyway:
    image: simpletodo-flyway
    command: migrate
    volumes:
      - ./flyway/config:/flyway/conf
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
