FROM gradle:6.9.2-jdk11 AS build

COPY build.gradle /build/
COPY src /build/src/

WORKDIR /build/

RUN gradle build --no-daemon

FROM adoptopenjdk/openjdk11:latest

WORKDIR /app

COPY --from=build /build/build/libs/*.jar /app/simpletodo-server.jar

COPY docker/wait-for-it.sh wait-for-it.sh 
RUN chmod +x wait-for-it.sh

ENTRYPOINT ["./wait-for-it.sh" , "db:3306" , "--strict" , "--timeout=30" , "--" , "java", "-jar","/app/simpletodo-server.jar"]