CREATE TABLE IF NOT EXISTS roles (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	STR_NAME VARCHAR(20),
	CONSTRAINT pk_roles
		PRIMARY KEY ( NR_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS workspaces (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	STR_NAME VARCHAR(100),
	JSON_DATA JSON CHECK (JSON_VALID(json_data)),
	CONSTRAINT pk_workspaces
		PRIMARY KEY ( NR_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS lists (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	STR_NAME VARCHAR(100),
	NR_WORKSPACE_ID BINARY(16) NOT NULL,
	JSON_DATA JSON CHECK (JSON_VALID(json_data)),
	CONSTRAINT pk_lists
		PRIMARY KEY ( NR_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS users (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	STR_USERNAME VARCHAR(100),
	STR_EMAIL VARCHAR(100),
	STR_PASSWORD VARCHAR(100),
	JSON_DATA JSON CHECK (JSON_VALID(json_data)),
	CONSTRAINT pk_users
		PRIMARY KEY ( NR_ID ),
	UNIQUE KEY uk_username ( STR_USERNAME ),
	UNIQUE KEY uk_email ( STR_EMAIL )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS todos (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	STR_MSG VARCHAR(1024),
	DATE_DUE TIMESTAMP NULL,
	STATUS_DONE TINYINT(1) NOT NULL DEFAULT 0,
	NR_LIST_ID BINARY(16) NOT NULL,
	JSON_DATA JSON CHECK (JSON_VALID(json_data)),
	CONSTRAINT pk_todos
		PRIMARY KEY (NR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS user_roles (
	NR_USER_ID BINARY(16) NOT NULL,
	NR_ROLE_ID BINARY(16) NOT NULL,
	CONSTRAINT pk_user_roles_id
		PRIMARY KEY ( NR_USER_ID, NR_ROLE_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS workspace_users (
	NR_WORKSPACE_ID BINARY(16) NOT NULL,
	NR_USER_ID BINARY(16) NOT NULL,
	CONSTRAINT pk_workspace_users_id
		PRIMARY KEY ( NR_WORKSPACE_ID, NR_USER_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS workspace_lists (
	NR_WORKSPACE_ID BINARY(16) NOT NULL,
	NR_LIST_ID BINARY(16) NOT NULL,
	CONSTRAINT pk_workspace_lists_id
		PRIMARY KEY ( NR_WORKSPACE_ID, NR_LIST_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS list_todos (
	NR_LIST_ID BINARY(16) NOT NULL,
	NR_TODO_ID BINARY(16) NOT NULL,
	CONSTRAINT pk_list_todos_id
		PRIMARY KEY ( NR_LIST_ID, NR_TODO_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS forgotpasswordtokens (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	NR_USER_ID BINARY(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
