ALTER TABLE users ADD STATUS_ACTIVATED TINYINT(1) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS useractivationtokens (
	NR_ID BINARY(16) NOT NULL DEFAULT UUID(),
	NR_USER_ID BINARY(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;